CREATE TABLE [yos].[ETLLOAD0312] (
    [ETLLoadID]                          BIGINT           IDENTITY (1, 1) NOT NULL,
    [ResourceAgencyNum]                  VARCHAR (50)     NULL,
    [PublicName]                         VARCHAR (2000)   NULL,
    [AlternateName]                      VARCHAR (2000)   NULL,
    [OfficialName]                       VARCHAR (2000)   NULL,
    [TaxonomyLevelName]                  VARCHAR (50)     NULL,
    [ParentAgency]                       VARCHAR (2000)   NULL,
    [ParentAgencyNum]                    VARCHAR (50)     NULL,
    [RecordOwner]                        VARCHAR (50)     NULL,
    [UniqueIDPriorSystem]                VARCHAR (50)     NULL,
    [MailingAttentionName]               VARCHAR (50)     NULL,
    [MailingAddress1]                    VARCHAR (2000)   NULL,
    [MailingAddress2]                    VARCHAR (2000)   NULL,
    [MailingCity]                        VARCHAR (50)     NULL,
    [MailingStateProvince]               VARCHAR (50)     NULL,
    [MailingPostalCode]                  VARCHAR (50)     NULL,
    [MailingCountry]                     VARCHAR (50)     NULL,
    [MailingAddressIsPrivate]            VARCHAR (50)     NULL,
    [PhysicalAddress1]                   VARCHAR (2000)   NULL,
    [PhysicalAddress2]                   VARCHAR (2000)   NULL,
    [PhysicalCity]                       VARCHAR (50)     NULL,
    [PhysicalCounty]                     VARCHAR (50)     NULL,
    [PhysicalStateProvince]              VARCHAR (50)     NULL,
    [PhysicalPostalCode]                 VARCHAR (50)     NULL,
    [PhysicalCountry]                    VARCHAR (50)     NULL,
    [PhysicalAddressIsPrivate]           VARCHAR (50)     NULL,
    [OtherAddress1]                      VARCHAR (2000)   NULL,
    [OtherAddress2]                      VARCHAR (2000)   NULL,
    [OtherCity]                          VARCHAR (50)     NULL,
    [OtherCounty]                        VARCHAR (50)     NULL,
    [OtherStateProvince]                 VARCHAR (50)     NULL,
    [OtherPostalCode]                    VARCHAR (50)     NULL,
    [OtherCountry]                       VARCHAR (50)     NULL,
    [Latitude]                           NUMERIC (18, 10) NULL,
    [Longitude]                          NUMERIC (18, 10) NULL,
    [HoursOfOperation]                   VARCHAR (2000)   NULL,
    [Phone1Number]                       VARCHAR (2000)   NULL,
    [Phone1Name]                         VARCHAR (2000)   NULL,
    [Phone1Description]                  VARCHAR (2000)   NULL,
    [Phone1IsPrivate]                    BIT              NULL,
    [Phone1Type]                         VARCHAR (50)     NULL,
    [Phone2Number]                       VARCHAR (50)     NULL,
    [Phone2Name]                         VARCHAR (50)     NULL,
    [Phone2Description]                  VARCHAR (2000)   NULL,
    [Phone2IsPrivate]                    BIT              NULL,
    [Phone2Type]                         VARCHAR (50)     NULL,
    [Phone3Number]                       VARCHAR (50)     NULL,
    [Phone3Name]                         VARCHAR (50)     NULL,
    [Phone3Description]                  VARCHAR (2000)   NULL,
    [Phone3IsPrivate]                    BIT              NULL,
    [Phone3Type]                         VARCHAR (50)     NULL,
    [Phone4Number]                       VARCHAR (50)     NULL,
    [Phone4Name]                         VARCHAR (50)     NULL,
    [Phone4Description]                  VARCHAR (2000)   NULL,
    [Phone4IsPrivate]                    BIT              NULL,
    [Phone4Type]                         VARCHAR (50)     NULL,
    [Phone5Number]                       VARCHAR (50)     NULL,
    [Phone5Name]                         VARCHAR (50)     NULL,
    [Phone5Description]                  VARCHAR (2000)   NULL,
    [Phone5IsPrivate]                    BIT              NULL,
    [Phone5Type]                         VARCHAR (50)     NULL,
    [PhoneFax]                           VARCHAR (50)     NULL,
    [PhoneFaxDescription]                VARCHAR (2000)   NULL,
    [PhoneFaxIsPrivate]                  BIT              NULL,
    [PhoneTTY]                           VARCHAR (50)     NULL,
    [PhoneTTYDescription]                VARCHAR (2000)   NULL,
    [PhoneTTYIsPrivate]                  BIT              NULL,
    [PhoneTollFree]                      VARCHAR (50)     NULL,
    [PhoneTollFreeDescription]           VARCHAR (2000)   NULL,
    [PhoneTollFreeIsPrivate]             BIT              NULL,
    [PhoneNumberHotline]                 VARCHAR (50)     NULL,
    [PhoneNumberHotlineDescription]      VARCHAR (2000)   NULL,
    [PhoneNumberHotlineIsPrivate]        BIT              NULL,
    [PhoneNumberBusinessLine]            VARCHAR (50)     NULL,
    [PhoneNumberBusinessLineDescription] VARCHAR (2000)   NULL,
    [PhoneNumberBusinessLineIsPrivate]   BIT              NULL,
    [PhoneNumberOutOfArea]               VARCHAR (50)     NULL,
    [PhoneNumberOutOfAreaDescription]    VARCHAR (2000)   NULL,
    [PhoneNumberOutOfAreaIsPrivate]      BIT              NULL,
    [PhoneNumberAfterHours]              VARCHAR (50)     NULL,
    [PhoneNumberAfterHoursDescription]   VARCHAR (2000)   NULL,
    [PhoneNumberAfterHoursIsPrivate]     BIT              NULL,
    [EmailAddressMain]                   VARCHAR (2000)   NULL,
    [WebsiteAddress]                     VARCHAR (2000)   NULL,
    [AgencyStatus]                       VARCHAR (50)     NULL,
    [AgencyClassification]               VARCHAR (50)     NULL,
    [AgencyDescription]                  VARCHAR (MAX)    NULL,
    [SearchHints]                        VARCHAR (2000)   NULL,
    [CoverageArea]                       VARCHAR (2000)   NULL,
    [CoverageAreaText]                   VARCHAR (2000)   NULL,
    [Eligibility]                        VARCHAR (2000)   NULL,
    [EligibilityAdult]                   BIT              NULL,
    [EligibilityChild]                   BIT              NULL,
    [EligibilityFamily]                  BIT              NULL,
    [EligibilityFemale]                  BIT              NULL,
    [EligibilityMale]                    BIT              NULL,
    [EligibilityTeen]                    BIT              NULL,
    [SeniorWorkerName]                   VARCHAR (50)     NULL,
    [SeniorWorkerTitle]                  VARCHAR (2000)   NULL,
    [SeniorWorkerEmailAddress]           VARCHAR (2000)   NULL,
    [SeniorWorkerPhoneNumber]            VARCHAR (50)     NULL,
    [SeniorWorkerIsPrivate]              VARCHAR (50)     NULL,
    [MainContactName]                    VARCHAR (2000)   NULL,
    [MainContactTitle]                   VARCHAR (2000)   NULL,
    [MainContactEmailAddress]            VARCHAR (2000)   NULL,
    [MainContactPhoneNumber]             VARCHAR (50)     NULL,
    [MainContactType]                    VARCHAR (50)     NULL,
    [MainContactIsPrivate]               VARCHAR (50)     NULL,
    [LicenseAccreditation]               VARCHAR (50)     NULL,
    [IRSStatus]                          VARCHAR (50)     NULL,
    [FEIN]                               VARCHAR (50)     NULL,
    [YearIncorporated]                   VARCHAR (50)     NULL,
    [AnnualBudgetTotal]                  VARCHAR (50)     NULL,
    [LegalStatus]                        VARCHAR (50)     NULL,
    [SourceOfFunds]                      VARCHAR (50)     NULL,
    [ExcludeFromWebsite]                 VARCHAR (50)     NULL,
    [ExcludeFromDirectory]               VARCHAR (50)     NULL,
    [DisabilitiesAccess]                 VARCHAR (2000)   NULL,
    [PhysicalLocationDescription]        VARCHAR (2000)   NULL,
    [BusServiceAccess]                   VARCHAR (2000)   NULL,
    [PublicAccessTransportation]         VARCHAR (2000)   NULL,
    [FeeStructureSource]                 VARCHAR (2000)   NULL,
    [ApplicationProcess]                 VARCHAR (2000)   NULL,
    [ResourceInfo]                       VARCHAR (2000)   NULL,
    [DocumentsRequired]                  VARCHAR (2000)   NULL,
    [LanguagesOffered]                   VARCHAR (2000)   NULL,
    [LanguagesOfferedList]               VARCHAR (2000)   NULL,
    [AvailabilityNumberOfTimes]          VARCHAR (2000)   NULL,
    [AvailabilityFrequency]              VARCHAR (2000)   NULL,
    [AvailabilityPeriod]                 VARCHAR (50)     NULL,
    [ServiceNotAlwaysAvailability]       VARCHAR (50)     NULL,
    [CapacityType]                       VARCHAR (2000)   NULL,
    [ServiceCapacity]                    VARCHAR (2000)   NULL,
    [NormalWaitTime]                     VARCHAR (2000)   NULL,
    [TemporaryMessage]                   VARCHAR (2000)   NULL,
    [TemporaryMessageAppears]            DATETIME         NULL,
    [TemporaryMessageExpires]            DATETIME         NULL,
    [EnteredOn]                          DATETIME         NULL,
    [UpdatedOn]                          DATETIME         NULL,
    [MadeInactiveOn]                     DATETIME         NULL,
    [InternalNotes]                      VARCHAR (2000)   NULL,
    [InternalNotesForEditorsAndViewers]  VARCHAR (2000)   NULL,
    [HighlightedResource]                BIT              NULL,
    [LastVerifiedOn]                     DATETIME         NULL,
    [LastVerifiedByName]                 VARCHAR (50)     NULL,
    [LastVerifiedByTitle]                VARCHAR (2000)   NULL,
    [LastVerifiedByPhoneNumber]          VARCHAR (50)     NULL,
    [LastVerifiedByEmailAddress]         VARCHAR (2000)   NULL,
    [LastVerificationApprovedBy]         VARCHAR (50)     NULL,
    [AvailableForDirectory]              VARCHAR (50)     NULL,
    [AvailableForReferral]               VARCHAR (50)     NULL,
    [AvailableForResearch]               VARCHAR (50)     NULL,
    [PreferredProvider]                  BIT              NULL,
    [ConnectsToSiteNum]                  VARCHAR (50)     NULL,
    [ConnectsToProgramNum]               VARCHAR (50)     NULL,
    [LanguageOfRecord]                   VARCHAR (50)     NULL,
    [CurrentWorkflowStepCode]            VARCHAR (50)     NULL,
    [VolunteerOpportunities]             VARCHAR (50)     NULL,
    [VolunteerDuties]                    VARCHAR (2000)   NULL,
    [Categories]                         VARCHAR (50)     NULL,
    [TaxonomyTerm]                       VARCHAR (2000)   NULL,
    [TaxonomyTerms]                      VARCHAR (2000)   NULL,
    [TaxonomyTermsNotDeactivated]        VARCHAR (2000)   NULL,
    [TaxonomyCodes]                      VARCHAR (2000)   NULL,
    [Coverage]                           VARCHAR (MAX)    NULL,
    [WorkHours]                          VARCHAR (2000)   NULL,
    [CustomServicesToLGBTQ]              VARCHAR (2000)   NULL,
    [CustomAutomatedStatus]              VARCHAR (2000)   NULL,
    [CustomBatchID]                      VARCHAR (50)     NULL,
    [CustomProgramHarmReductionService]  VARCHAR (50)     NULL,
    [CustomEligibilitybyAge]             VARCHAR (2000)   NULL,
    [CustomEligibilityByGender]          VARCHAR (2000)   NULL,
    [CustomLanguagePrefer]               VARCHAR (2000)   NULL,
    [CustomBilingualService]             VARCHAR (2000)   NULL,
    [CustomManualStatus]                 VARCHAR (50)     NULL,
    [CustomMCYSAccountNumber]            VARCHAR (2000)   NULL,
    [CustomAnonymityPolicy]              VARCHAR (MAX)    NULL,
    [CustomSuggestKeyword]               VARCHAR (MAX)    NULL,
    [CustomRecordType]                   VARCHAR (50)     NULL,
    [CustomSourceDatabase]               VARCHAR (50)     NULL,
    [changedDate]                        DATETIME         NULL,
    [createdDate]                        DATETIME         NULL
);

