CREATE TABLE [yos].[InComplete] (
    [ETLLoadID]                BIGINT           NULL,
    [Incomplete]               NVARCHAR (2000)  NULL,
    [ResourceAgencyNum]        NVARCHAR (2000)  NULL,
    [ClassicationID]           INT              NULL,
    [PublicName]               NVARCHAR (2000)  NULL,
    [AgencyDescription]        NVARCHAR (MAX)   NULL,
    [TaxonomyLevelNameID]      INT              NULL,
    [ParentAgencyNum]          NVARCHAR (2000)  NULL,
    [PhysicalAddress]          NVARCHAR (2000)  NULL,
    [PhysicalCityID]           INT              NULL,
    [PhysicalProvinceID]       INT              NULL,
    [PhysicalCountry]          NVARCHAR (2000)  NULL,
    [PhysicalPostalCode]       NVARCHAR (2000)  NULL,
    [PhysicalAddressIsPrivate] NVARCHAR (2000)  NULL,
    [Latitude]                 NUMERIC (18, 10) NULL,
    [Longitude]                NUMERIC (18, 10) NULL,
    [HoursOfOperation]         NVARCHAR (2000)  NULL,
    [Phone]                    NVARCHAR (2000)  NULL,
    [WebsiteAddress]           NVARCHAR (2000)  NULL,
    [Eligibility]              NVARCHAR (2000)  NULL,
    [DisabilitiesAccess]       NVARCHAR (2000)  NULL,
    [FeeStructureSource]       NVARCHAR (2000)  NULL,
    [ApplicationProcess]       NVARCHAR (2000)  NULL,
    [DocumentsRequired]        NVARCHAR (2000)  NULL,
    [LanguagesOfferedList]     NVARCHAR (2000)  NULL,
    [LanguageOfRecord]         NVARCHAR (2000)  NULL,
    [WorkHours]                NVARCHAR (2000)  NULL,
    [CustomEligibilitybyAge]   NVARCHAR (2000)  NULL,
    [createdDate]              DATETIME         CONSTRAINT [DF_Incomplete_createdDate] DEFAULT (getdate()) NULL
);

