CREATE TABLE [yos].[NewRam] (
    [ETLLoadID]                INT              NOT NULL,
    [ResourceAgencyNum]        NVARCHAR (50)    NULL,
    [Map]                      BIT              CONSTRAINT [DF_NewRam_Map] DEFAULT ((1)) NULL,
    [PublicName]               NVARCHAR (2000)  NULL,
    [AgencyDescription]        NVARCHAR (MAX)   NULL,
    [TaxonomyLevelNameID]      INT              NULL,
    [ParentAgencyNum]          NVARCHAR (50)    NULL,
    [PhysicalAddress]          NVARCHAR (2000)  NULL,
    [PhysicalCityID]           INT              NULL,
    [PhysicalProvinceID]       INT              NULL,
    [PhysicalCountry]          NVARCHAR (50)    CONSTRAINT [DF_NewRam_PhysicalCountry] DEFAULT ('Canada') NULL,
    [PhysicalPostalCode]       NVARCHAR (50)    NULL,
    [PhysicalAddressIsPrivate] NVARCHAR (50)    NULL,
    [Latitude]                 NUMERIC (18, 10) NULL,
    [Longitude]                NUMERIC (18, 10) NULL,
    [HoursOfOperation]         NVARCHAR (2000)  NULL,
    [Phone]                    NVARCHAR (2000)  NULL,
    [WebsiteAddress]           NVARCHAR (2000)  NULL,
    [Eligibility]              NVARCHAR (2000)  NULL,
    [DisabilitiesAccess]       NVARCHAR (2000)  NULL,
    [FeeStructureSource]       NVARCHAR (2000)  NULL,
    [ApplicationProcess]       NVARCHAR (2000)  NULL,
    [DocumentsRequired]        NVARCHAR (2000)  NULL,
    [LanguagesOfferedList]     NVARCHAR (2000)  NULL,
    [LanguageOfRecord]         NVARCHAR (50)    NULL,
    [WorkHours]                NVARCHAR (2000)  NULL,
    [CustomEligibilitybyAge]   NVARCHAR (2000)  NULL,
    [changedDate]              DATETIME         NULL,
    [createdDate]              DATETIME         NULL,
    CONSTRAINT [PK_NewRam] PRIMARY KEY CLUSTERED ([ETLLoadID] ASC),
    CONSTRAINT [FK_NewRam_CityLocation] FOREIGN KEY ([PhysicalCityID]) REFERENCES [dbo].[CityLocation] ([CityId]),
    CONSTRAINT [FK_NewRam_Province] FOREIGN KEY ([PhysicalProvinceID]) REFERENCES [dbo].[Province] ([ProvinceID]),
    CONSTRAINT [FK_NewRam_TaxonomyLevelName] FOREIGN KEY ([TaxonomyLevelNameID]) REFERENCES [dbo].[TaxonomyLevelName] ([TaxonomyLevelNameID])
);

