CREATE TABLE [dbo].[InComplete_RamResource] (
    [Incomplete]               NVARCHAR (20)    NULL,
    [ETLLoadID]                INT              NOT NULL,
    [ResourceAgencyNum]        NVARCHAR (50)    NULL,
    [Map]                      NVARCHAR (50)    CONSTRAINT [DF_InCompleteRamResource_Map] DEFAULT ((1)) NOT NULL,
    [SubCategoryID]            INT              NOT NULL,
    [TOPCategoryID]            INT              NOT NULL,
    [PublicName]               NVARCHAR (2000)  NULL,
    [AgencyDescription]        NVARCHAR (MAX)   NULL,
    [TaxonomyLevelNameID]      INT              NULL,
    [ParentAgencyNum]          NVARCHAR (50)    NULL,
    [PhysicalAddress]          NVARCHAR (2000)  NULL,
    [PhysicalCityID]           INT              NULL,
    [PhysicalProvinceID]       INT              NULL,
    [PhysicalCountry]          NVARCHAR (50)    CONSTRAINT [DF_InCompleteRamResource_PhysicalCountry] DEFAULT ('Canada') NULL,
    [PhysicalPostalCode]       NVARCHAR (50)    NULL,
    [PhysicalAddressIsPrivate] NVARCHAR (50)    NULL,
    [Latitude]                 NUMERIC (18, 10) NULL,
    [Longitude]                NUMERIC (18, 10) NULL,
    [HoursOfOperation]         NVARCHAR (2000)  NULL,
    [Phone]                    NVARCHAR (2000)  NULL,
    [WebsiteAddress]           NVARCHAR (2000)  NULL,
    [Eligibility]              NVARCHAR (2000)  NULL,
    [DisabilitiesAccess]       NVARCHAR (2000)  NULL,
    [FeeStructureSource]       NVARCHAR (2000)  NULL,
    [ApplicationProcess]       NVARCHAR (2000)  NULL,
    [DocumentsRequired]        NVARCHAR (2000)  NULL,
    [LanguagesOfferedList]     NVARCHAR (2000)  NULL,
    [LanguageOfRecord]         NVARCHAR (50)    NULL,
    [WorkHours]                NVARCHAR (2000)  NULL,
    [CustomEligibilitybyAge]   NVARCHAR (2000)  NULL,
    [CoverageArea]             NVARCHAR (2000)  NULL,
    [Coverage]                 NVARCHAR (MAX)   NULL,
    [NormalWaitTime]           NVARCHAR (2000)  NULL,
    [changedDate]              DATETIME         NULL,
    [createdDate]              DATETIME         CONSTRAINT [DF_InCompleteRamResource_createdDate] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_InComplete_RamResource] PRIMARY KEY CLUSTERED ([ETLLoadID] ASC, [Map] ASC, [SubCategoryID] ASC, [TOPCategoryID] ASC)
);

