CREATE TABLE [dbo].[Map] (
    [ETLLoadID]              INT              NOT NULL,
    [ResourceAgencyNum]      NVARCHAR (50)    NULL,
    [Map]                    NVARCHAR (50)    CONSTRAINT [DF_Map_Map] DEFAULT (N'Mapped') NULL,
    [SubCategoryID]          INT              NOT NULL,
    [TopCategoryID]          INT              NOT NULL,
    [PublicName]             NVARCHAR (2000)  NULL,
    [AgencyDescription]      NVARCHAR (MAX)   NULL,
    [PhysicalAddress]        NVARCHAR (2000)  NULL,
    [PhysicalCityID]         INT              NULL,
    [PhysicalCity]           NVARCHAR (500)   NULL,
    [PhysicalProvinceID]     INT              NULL,
    [PhysicalProvince]       NVARCHAR (50)    NULL,
    [PhysicalCountry]        NVARCHAR (50)    NULL,
    [PhysicalPostalCode]     NVARCHAR (50)    NULL,
    [Latitude]               NUMERIC (18, 10) NULL,
    [Longitude]              NUMERIC (18, 10) NULL,
    [HoursOfOperation]       NVARCHAR (2000)  NULL,
    [Phone]                  NVARCHAR (2000)  NULL,
    [WebsiteAddress]         NVARCHAR (2000)  NULL,
    [Eligibility]            NVARCHAR (2000)  NULL,
    [DisabilitiesAccess]     NVARCHAR (2000)  NULL,
    [FeeStructureSource]     NVARCHAR (2000)  NULL,
    [ApplicationProcess]     NVARCHAR (2000)  NULL,
    [DocumentsRequired]      NVARCHAR (2000)  NULL,
    [LanguagesOfferedList]   NVARCHAR (2000)  NULL,
    [LanguageOfRecord]       NVARCHAR (50)    NULL,
    [WorkHours]              NVARCHAR (2000)  NULL,
    [CustomEligibilitybyAge] NVARCHAR (2000)  NULL,
    [CoverageArea]           NVARCHAR (2000)  NULL,
    [Coverage]               NVARCHAR (MAX)   NULL,
    [NormalWaitTime]         NVARCHAR (2000)  NULL,
    [createdDate]            DATETIME         CONSTRAINT [DF_Map_createdDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_Map] PRIMARY KEY CLUSTERED ([ETLLoadID] ASC, [SubCategoryID] ASC, [TopCategoryID] ASC),
    CONSTRAINT [FK_Map_KHPCategory] FOREIGN KEY ([TopCategoryID]) REFERENCES [yos].[KHPCategory] ([KHPCategoryID])
);

