CREATE TABLE [dbo].[updatelog] (
    [updatelogid]                  INT            IDENTITY (1, 1) NOT NULL,
    [UpdatedDate]                  DATE           CONSTRAINT [DF_updatelog_UpdatedDate] DEFAULT (CONVERT([date],getdate())) NULL,
    [UpdateDesc]                   NVARCHAR (500) NULL,
    [CommunityResource]            INT            NULL,
    [CommunityResource_en]         INT            CONSTRAINT [DF_updatelog_CommunityResource_en] DEFAULT ((0)) NULL,
    [CommunityResource_fr]         INT            CONSTRAINT [DF_updatelog_CommunityResource_fr] DEFAULT ((0)) NULL,
    [Agency]                       INT            CONSTRAINT [DF_updatelog_Agency] DEFAULT ((0)) NULL,
    [Site]                         INT            CONSTRAINT [DF_updatelog_Site] DEFAULT ((0)) NULL,
    [Program]                      INT            CONSTRAINT [DF_updatelog_Program] DEFAULT ((0)) NULL,
    [ProgramAtSite]                INT            CONSTRAINT [DF_updatelog_ProgramAtSite] DEFAULT ((0)) NULL,
    [PCoverage]                    INT            NULL,
    [PCustomEligibilitybyAge]      INT            NULL,
    [ETLLoadID_TaxonomyCode]       INT            NULL,
    [InterestTaxonomyID_ETLLoadID] INT            NULL,
    [KeyWords]                     INT            NULL,
    [PWorkHour]                    INT            NULL,
    [ProgramRAW]                   INT            NULL,
    [RAMRAW]                       INT            NULL,
    [TaxonomyRAW]                  INT            NULL,
    [SuggestionWords]              INT            NULL,
    [RAMResource]                  INT            NULL,
    [RAMResource_fr]               INT            NULL,
    [Mapped]                       INT            NULL,
    [Lists]                        INT            NULL,
    [Boths]                        INT            NULL,
    [Shelter]                      INT            NULL,
    [IPublicName]                  INT            NULL,
    [ILatLong]                     INT            NULL,
    [IAddress]                     INT            NULL,
    [IAgencyDesc]                  INT            NULL,
    [IDisabilitiesAccess]          INT            NULL,
    [ILanguagesOfferedList]        INT            NULL,
    [ICoverageArea]                INT            NULL,
    [ICoverage]                    INT            NULL,
    [changedDate]                  DATETIME       NULL,
    [CreatedDate]                  DATETIME       CONSTRAINT [DF_updatelog_CreatedDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_updatelog] PRIMARY KEY CLUSTERED ([updatelogid] ASC)
);

